version: '3.8'
services:
  flask-app:
    container_name: flask_app
    image: ghcr.io/pegahr1996/riyadh_dictionary:main
    pull_policy: always
    volumes:
      - ./socket:/tmp
    environment:
      - FLASK_ENV=production
    restart: unless-stopped