name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with ruff
      run: |
        pip install ruff
        ruff .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        load: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/riyadh_dictionary:${{ github.sha }}
          ${{ github.ref == 'refs/heads/main' && 'ghcr.io/${{ github.repository_owner }}/riyadh_dictionary:latest' }}

    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /opt/flask_app/
          # remove existing docker-compose.yml file
          rm -f docker-compose.yml
          # copy the new docker-compose.yml file to server
          scp docker-compose.yml ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/opt/flask_app/docker-compose.yml
          # assuming docker-compose is installed on the server, pull the new images and bring up the services
          docker-compose -f /opt/flask_app/docker-compose.yml down
          docker-compose -f /opt/flask_app/docker-compose.yml up -d